drf/urls.py
# flake8: noqa
from django.urls import include, path
from rest_framework import routers
from drf import views

# router = routers.DefaultRouter()
# router.register(r'students', views.StudentList)
# router.register(r'students/<int:student_id>', views.StudentDetails)
# router.register(r'groups', views.GroupViewSet)
# router.register(r'teachers', views.TeacherViewSet)

app_name = 'drf'


urlpatterns = [
    # path('', include(router.urls)),
    path('students/', views.StudentList.as_view(), name='StudentList'),
    path('students/<int:student_id>', views.StudentDetails.as_view(), name='StudentDetails'),
    path('groups/', views.GroupList.as_view(), name='GroupList'),
    path('groups/<int:group_id>', views.GroupDetails.as_view(), name='GroupDetails'),
    path('teachers/', views.TeacherList.as_view(), name='TeacherList')
]

school_m/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('drf/', include('drf.urls')),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teacher.urls')),
    path('groups/', include('group.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

teacher/urls.py
from django.urls import path

from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.get_teachers, name='list'),
    path('<int:teacher_id>/edit/', views.edit_teacher, name='edit'),
    path('create/', views.create_teachers, name='create'),
    path('<int:teacher_id>/delete/', views.delete_teacher, name='delete'),
]

teacher/models.py
from django.db import models
# flake8: noqa
from students.validator import validate_phone


class Teacher(models.Model):
    id = models.BigAutoField
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    age = models.IntegerField()
    phone = models.CharField(
        max_length=13,
        validators=[validate_phone]
    )

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.first_name} - {self.last_name} - {self.age}y.o.'

teacher/forms.py
from django import forms

from teacher.models import Teacher


class TeacherForm(forms.ModelForm):

    def clean(self):
        age = self.cleaned_data['age']

        if age < 18:
            self.add_error('age', 'Too small age for being a teacher')
        if age > 65:
            self.add_error('age', 'Too old for being a teacher')

    class Meta:
        model = Teacher
        fields = (
            'first_name',
            'last_name',
            'age',
            'phone',
        )

teacher/views.py
import random

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from faker import Faker

from teacher.forms import TeacherForm
from teacher.models import Teacher


def get_teachers(request):
    queryset = Teacher.objects.all()
    return render(request, 'teacher/index.html',
                  context={'teachers': queryset})


def edit_teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, pk=teacher_id)

    if request.method == 'GET':
        form = TeacherForm(instance=teacher)

        return render(request, 'teacher/edit.html', context={'form': form})

    if request.method == 'POST':
        form = TeacherForm(request.POST, instance=teacher)
        if form.is_valid():
            form.save()
            return redirect(reverse('teacher:list'))

        return render(request, 'teacher/edit.html', context={'form': form})

    return HttpResponse(status=405)


@require_http_methods(['GET', 'POST'])
def delete_teacher(request, teacher_id):
    teacher = get_object_or_404(Teacher, pk=teacher_id)

    if request.method == 'POST':
        teacher.delete()
        return HttpResponseRedirect(reverse('teacher:list'))

    return render(request, 'teacher/edit.html')


@require_http_methods(['GET', 'POST'])
def create_teachers(request):

    if request.method == 'GET':
        fake = Faker()

        data = {
            'first_name': fake.first_name(),
            'last_name': fake.last_name(),
            'age': random.randint(18, 65),
            'phone': '+380967195593',
        }

        form = TeacherForm(initial=data)

        return render(request, 'teacher/create.html',
                      context={'form': form})

    form = TeacherForm(request.POST)

    if form.is_valid():
        form.save()

        return HttpResponseRedirect(reverse('teacher:list'))

    return HttpResponse(str(form.errors), status=400)

teacher/templates/teacher/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <title>Create Teacher</title>
</head>
<body>

<form action="{% url 'teacher:create' %}" method="post">

    {{ form.as_p }}

    <input type="submit">
    {% csrf_token %}



</form>

</body>
</html>

teacher/templates/teacher/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <title>Edit Teacher</title>
</head>
<body>

<form action='{% url 'teacher:edit' teacher_id=form.instance.id %}' method='post'>

    {{ form.as_p }}

    <input type='submit' value='EDIT✔' style='background-color: Lime;'>
    {% csrf_token %}

</form>

<form action='{% url 'teacher:delete' teacher_id=form.instance.id%}' method='post'>
<br>
    <input type='submit' value='DELETE✖' style='background-color: Red;'>
    {% csrf_token %}

</form>


</body>
</html>

teacher/templates/teacher/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher list</title>
</head>
<body>

<h1>Look at our teachers<3</h1>

<a href="{% url 'teacher:create' %}">Create Teacher</a>

<h3>Teacher list</h3>

<ul>
    {% for teacher in teachers %}

        <li>
            <a href="{% url 'teacher:edit' teacher_id=teacher.pk %}">{{ forloop.counter }}. {{ teacher.full_name }}</a>
        </li>

    {% endfor %}


</ul>

</body>
</html>