drf/urls.py
# flake8: noqa
from django.urls import include, path
from rest_framework import routers
from drf import views

# router = routers.DefaultRouter()
# router.register(r'students', views.StudentList)
# router.register(r'students/<int:student_id>', views.StudentDetails)
# router.register(r'groups', views.GroupViewSet)
# router.register(r'teachers', views.TeacherViewSet)

app_name = 'drf'


urlpatterns = [
    # path('', include(router.urls)),
    path('students/', views.StudentList.as_view(), name='StudentList'),
    path('students/<int:student_id>', views.StudentDetails.as_view(), name='StudentDetails'),
    path('groups/', views.GroupList.as_view(), name='GroupList'),
    path('groups/<int:group_id>', views.GroupDetails.as_view(), name='GroupDetails'),
    path('teachers/', views.TeacherList.as_view(), name='TeacherList')
]

group/urls.py
from django.urls import path

from . import views

app_name = 'group'
urlpatterns = [
    path('', views.get_groups, name='list'),
    path('<int:group_id>/edit/', views.edit_group, name='edit'),
    path('create/', views.create_groups, name='create'),
    path('<int:group_id>/delete/', views.delete_group, name='delete'),
]

school_m/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('drf/', include('drf.urls')),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teacher.urls')),
    path('groups/', include('group.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

group/models.py
import datetime
from datetime import timezone

from django.db import models
# flake8: noqa
from students.models import Student
from teacher.models import Teacher


class Group(models.Model):
    student = models.ManyToManyField(Student)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)
    id = models.BigAutoField
    group_name = models.CharField(max_length=64)
    group_direction = models.CharField(max_length=64)
    group_size = models.PositiveSmallIntegerField()

    # def was_published_recently(self):
    #     return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    # was_published_recently.admin_order_field = 'pub_date'
    # was_published_recently.boolean = True
    # was_published_recently.short_description = 'Published recently?'

    @property
    def full_name(self):
        return f'{self.group_name} {self.group_direction} {self.group_size} in it'

    def get_full_info(self):
        return f'{self.id}{self.group_name} {self.group_direction},' \
               f' group_size={self.group_size}'

group/forms.py
from django import forms

from group.models import Group


class GroupForm(forms.ModelForm):

    def clean(self):
        group_size = self.cleaned_data['group_size']

        if group_size < 6:
            self.add_error('group_size', 'Too small size of group')
        if group_size > 20:
            self.add_error('group_size', 'Too large size of group')

    class Meta:
        model = Group
        fields = (
            'group_name',
            'group_direction',
            'group_size',
        )

group/views.py
import random

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from faker import Faker

from group.forms import GroupForm
from group.models import Group


def get_groups(request):
    queryset = Group.objects.all()
    return render(request, 'group/index.html',
                  context={'groups': queryset})


def edit_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if request.method == 'GET':
        form = GroupForm(instance=group)

        return render(request, 'group/edit.html', context={'form': form})

    if request.method == 'POST':
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return redirect(reverse('group:list'))

        return render(request, 'group/edit.html', context={'form': form})

    return HttpResponse(status=405)


@require_http_methods(['GET', 'POST'])
def delete_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)

    if request.method == 'POST':
        group.delete()
        return HttpResponseRedirect(reverse('group:list'))

    return render(request, 'group/edit.html')


@require_http_methods(['GET', 'POST'])
def create_groups(request):

    if request.method == 'GET':
        fake = Faker()

        data = {
            'group_name': fake.license_plate(),
            'group_direction': fake.language_name(),
            'group_size': random.randint(6, 20),
        }

        form = GroupForm(initial=data)

        return render(request, 'group/create.html',
                      context={'form': form})

    form = GroupForm(request.POST)

    if form.is_valid():
        form.save()

        return HttpResponseRedirect(reverse('group:list'))

    return HttpResponse(str(form.errors), status=400)

group/templates/group/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <title>Create Group</title>
</head>
<body>

<form action="{% url 'group:create' %}" method="post">

    {{ form.as_p }}

    <input type="submit">
    {% csrf_token %}



</form>

</body>
</html>

group/templates/group/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <title>Edit Group</title>
</head>
<body>

<form action='{% url 'group:edit' group_id=form.instance.id %}' method='post'>

    {{ form.as_p }}

    <input type='submit' value='EDIT✔' style='background-color: Lime;'>
    {% csrf_token %}

</form>

<form action='{% url 'group:delete' group_id=form.instance.id%}' method='post'>
<br>
    <input type='submit' value='DELETE✖' style='background-color: Red;'>
    {% csrf_token %}

</form>


</body>
</html>

group/templates/group/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Group list</title>
</head>
<body>

<h1>Look at our groups<3</h1>

<a href="{% url 'group:create' %}">Create Group</a>

<h3>Group list</h3>

<ul>
    {% for group in groups %}

        <li>
            <a href="{% url 'group:edit' group_id=group.pk %}">{{ forloop.counter }}. {{ group.full_name }}</a>
        </li>

    {% endfor %}


</ul>

</body>
</html>