drf/urls.py
# flake8: noqa
from django.urls import include, path
from rest_framework import routers
from drf import views

# router = routers.DefaultRouter()
# router.register(r'students', views.StudentList)
# router.register(r'students/<int:student_id>', views.StudentDetails)
# router.register(r'groups', views.GroupViewSet)
# router.register(r'teachers', views.TeacherViewSet)

app_name = 'drf'


urlpatterns = [
    # path('', include(router.urls)),
    path('students/', views.StudentList.as_view(), name='StudentList'),
    path('students/<int:student_id>', views.StudentDetails.as_view(), name='StudentDetails'),
    path('groups/', views.GroupList.as_view(), name='GroupList'),
    path('groups/<int:group_id>', views.GroupDetails.as_view(), name='GroupDetails'),
    path('teachers/', views.TeacherList.as_view(), name='TeacherList')
]

school_m/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('drf/', include('drf.urls')),
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('teachers/', include('teacher.urls')),
    path('groups/', include('group.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

students/urls.py
from django.urls import path

from . import views

app_name = 'students'

urlpatterns = [
    path('', views.get_students, name='list'),
    path('<int:student_id>/edit/', views.edit_student,
         name='edit'),
    path('create/', views.create_students, name='create'),
    path('<int:student_id>/delete/', views.delete_student, name='delete'),
]

students/models.py
from django.db import models
# flake8: noqa
from students.validator import validate_phone
from teacher.models import Teacher


class Student(models.Model):
    teachers = models.ManyToManyField(Teacher)
    id = models.BigAutoField
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    age = models.PositiveSmallIntegerField()
    phone = models.CharField(
        max_length=13,
        validators=[validate_phone]
    )

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def get_full_info(self):
        return f'{self.id}{self.first_name} {self.last_name}, age={self.age}'


class Logger(models.Model):
    method = models.CharField(max_length=12)
    path = models.URLField(max_length=666)
    execution_time = models.FloatField(max_length=12)
    created = models.DateTimeField(auto_now_add=True)


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField(max_length=500)

    def __str__(self):
        return self.email

students/forms.py
from django import forms

from students.models import Contact
from students.models import Student


class StudentForm(forms.ModelForm):

    def clean(self):
        age = self.cleaned_data['age']

        if age < 5:
            self.add_error('age', 'Too small age for being a student')
        if age > 18:
            self.add_error('age', 'Too old for being a student')

    class Meta:
        model = Student
        fields = (
            'first_name',
            'last_name',
            'age',
            'phone',
        )


class ContactForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = (
            'name',
            'email',
            'message',
        )

students/views.py
import random

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from faker import Faker

from students.forms import StudentForm
from students.models import Student
from students.tasks import delete_log


def get_students(request):
    queryset = Student.objects.all()

    delete_log.delay()

    return render(request, 'students/index.html',
                  context={'students': queryset})


def edit_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)

    if request.method == 'GET':
        form = StudentForm(instance=student)

        return render(request, 'students/edit.html', context={'form': form})

    if request.method == 'POST':
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect(reverse('students:list'))

        return render(request, 'students/edit.html', context={'form': form})

    return HttpResponse(status=405)


@require_http_methods(['GET', 'POST'])
def delete_student(request, student_id):
    student = get_object_or_404(Student, pk=student_id)

    if request.method == 'POST':
        student.delete()
        return HttpResponseRedirect(reverse('students:list'))

    return render(request, 'students/edit.html')


@require_http_methods(['GET', 'POST'])
def create_students(request):

    if request.method == 'GET':
        fake = Faker()

        data = {
            'first_name': fake.first_name(),
            'last_name': fake.last_name(),
            'age': random.randint(5, 18),
            'phone': '+380967195593',
        }

        form = StudentForm(initial=data)

        return render(request, 'students/create.html',
                      context={'form': form})

    form = StudentForm(request.POST)

    if form.is_valid():
        form.save()

        return HttpResponseRedirect(reverse('students:list'))

    return HttpResponse(str(form.errors), status=400)

students/templates/students/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <title>Create Student</title>
</head>
<body>

<form action="{% url 'students:create' %}" method="post">

    {{ form.as_p }}

    <input type="submit">
    {% csrf_token %}



</form>

</body>
</html>

students/templates/students/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <title>Edit Student</title>
</head>
<body>

<form action='{% url 'students:edit' student_id=form.instance.id %}' method='post'>

    {{ form.as_p }}

    <input type='submit' value='EDIT✔' style='background-color: Lime;'>
    {% csrf_token %}

</form>

<form action='{% url 'students:delete' student_id=form.instance.id%}' method='post'>
<br>
    <input type='submit' value='DELETE✖' style='background-color: Red;'>
    {% csrf_token %}

</form>


</body>
</html>

students/templates/students/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Students list</title>
</head>
<body>

<h1>Welcome to our school))</h1>

<a href="{% url 'students:create' %}">Create Student</a>

<h3>Students list</h3>

<ul>
    {% for student in students %}

        <li>
            <a href="{% url 'students:edit' student_id=student.pk %}">{{ forloop.counter }}. {{ student.full_name }}</a>
        </li>

    {% endfor %}


</ul>

</body>
</html>